/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:27935961-1a9e-4c3c-b844-e59ee92e4e27",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_QH2OQGqwn",
    "aws_user_pools_web_client_id": "42t15cv6lgir247sb3d2leb62q",
    "oauth": {}
};


export default awsmobile;
